export default {
  en: {
    dic: {
      report: 'Report',
      filter: 'Filter',
      search: 'Search',
      add: 'Add',
      clone: 'Clone',
      edit: 'Edit',
      view: 'View',
      delete: 'Delete',
      deleted: 'Deleted.',
      _no: 'No.',
      code: 'Code',
      description: 'Description',
      status: 'Status',
      lastupdate: 'Last Update',
      nodata: 'No Data Available',
      show: 'Show',
      all: 'All',
      entries: 'entries',
      previous: 'Previous',
      next: 'Next',
      ok: 'Ok',
      save: 'Save',
      saved: 'Saved successfully.',
      cancel: 'Cancel',
      msgdel: 'Confirm data deletion.',
      msgappproved: 'Confirm Approved.',
      msgnotappproved: 'Confirm Not Approved.',
      password: 'Password',
      username: 'Username',
      confpass: 'Confirm Password',
      twofactor: '2 Factor',
      signin: 'Sign In',
      signup: 'Sign Up',
      resetpassword: 'Reset Password',
      confirm: 'Confirm',
      statusflag: 'Status Flag',
      grouptype: 'Group Type',
      approval: 'Approval',
      updateflag: 'Update Flag',
      approvalstep: 'Approval Step',
      step: 'Step',
      isapproved: 'Is Approved',
      actionflag: 'Action Flag',
      on: 'ON',
      off: 'OFF',
      yes: 'Yes',
      no: 'No',
      help: 'Help',
      textcolor: 'Text Color',
      more: 'More',
      hide: 'Hide',
      permissionblock: 'You don\'t have permission to access.'

    }
  },
  th: {
    dic: {
      report: 'รายงาน',
      filter: 'กรองข้อมูล',
      search: 'ค้นหา',
      add: 'เพิ่ม',
      clone: 'โคลน',
      view: 'ดู',
      edit: 'แก้ไข',
      delete: 'ลบ',
      deleted: 'ลบข้อมูลเรียบร้อย',
      _no: 'เลขที่',
      code: 'รหัส',
      description: 'คำอธิบาย',
      status: 'สถานะ',
      lastupdate: 'แก้ไขล่าสุด',
      nodata: 'ไม่มีข้อมูล',
      show: 'แสดง',
      all: 'ทั้งหมด',
      entries: 'รายการ',
      previous: 'ก่อนหน้า',
      next: 'ต่อไป',
      ok: 'ตกลง',
      save: 'บันทึก',
      saved: 'บันทึกข้อมูลเรียบร้อย',
      cancel: 'ยกเลิก',
      msgdel: 'ยืนยันการลบข้อมูล',
      msgappproved: 'ยืนยันการอนุมัติ',
      msgnotappproved: 'ยืนยันไม่อนุมัติ',
      password: 'รหัสผ่าน',
      username: 'Username',
      confpass: 'ยืนยันรหัสผ่าน',
      twofactor: 'รหัส 2 FA',
      signin: 'ลงชื่อเข้าใช้งาน',
      signup: 'สมัครสมาชิก',
      resetpassword: 'รีเซ็ตรหัสผ่าน',
      confirm: 'ยืนยัน',
      statusflag: 'แฟลกสถานะ',
      grouptype: 'ประเภทกลุ่ม',
      approval: 'การอนุมัติ',
      updateflag: 'การเปลี่ยนแปลง',
      approvalstep: 'ขั้นตอนการอนุมัติ',
      step: 'ขั้นตอน',
      isapproved: 'ได้รับการอนุมัติ',
      actionflag: 'การกระทำ',
      on: 'เปิด',
      off: 'ปิด',
      yes: 'ใช่',
      no: 'ไม่',
      help: 'ช่วยเหลือ',
      textcolor: 'สีตัวอักษร',
      more: 'เพิ่มเติม',
      hide: 'ซ่อน',
      permissionblock: 'คุณไม่ได้รับอนุญาตให้เข้าใช้งาน'

    }
  }
}
